### ISSUE TITLE
The VS Code Sidebar is not visible in the light theme

### ISSUE THREAD

**Issue by sergimula** [carloscuesta/sprinkles-vscode#43]
### Describe the bug

Using the light theme the VS Code Sidebar becomes unusable because the icons are mostly invisible. The problem is that the icons are in color white and the background is grey light.

![image](https://user-images.githubusercontent.com/57711472/225302624-92e92b1e-389b-4aea-9842-bf5d9194db61.png)

### Reproduction

Open VS Code with the sidebar enabled.

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 164.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 15.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/REPO/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey!

Thanks for reporting this, I believe this is caused by the fact that we’re not specifying the color of the icons at the theme level, see:

https://code.visualstudio.com/api/references/theme-color#activity-bar
