### ISSUE TITLE
🤔Question: What file icons do you use in the screenshot in this repo's README?

### ISSUE THREAD

**Issue by myferr** [carloscuesta/sprinkles-vscode#82]
As the title suggests, I'd like to know the name of the icon theme you have for the folders and files that you use in the screenshot in this repo's README. 👍

**Comment by carloscuesta** [comment]
Hey 👋🏼 

[Fluent Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons) is what I use for the file icons

**Comment by myferr** [comment]
Thanks! 👍
